///objInPalette(obj)
switch (argument0) {
    case SpikeU:
    case SpikeD:
    case SpikeL:
    case SpikeR:
    case Block:
    case MiniBlock:
    case MiniSpikeUp:
    case MiniSpikeDown:
    case MiniSpikeLeft:
    case MiniSpikeRight:
    case Platform:
    case OneTimePlatform:
    case Cherry:
    case Water1:
    case Water2:
    case Water3:
    case CatharsisWater:
    case NekoronAir:
    case UpdraftWater:
    case WaterNoJump:
    case ShootRefresherL:
    case ShootRefresherR:
    case WallJumpL:
    case WallJumpR:
    case GravFlip:
    case GravNormal:
    case JumpRefresher:
    case SlipBlock:
    case SidewaysPlatform:
    case LowGravField:
    case HighGravField:
    case LowSpeedField:
    case HighSpeedField:
    case PlayerStart:
    case SavePointHard:
    case SavePointFlip:
    case BulletBlock:
    case FakeWarp:
    case ZeroGravField:
    case KillBlock:
    case StarSingleJump:
    case StarDoubleJump:
    case StarTripleJump:
    case GravPlatformBoth:
    case GravPlatformUp:
    case GravPlatformDown:
    case ShootkidEnable:
    case ShootkidDisable:
    case DotkidEnable:
    case DotkidDisable:
    case VCoinGive:
    case VCoinTake:
    case Ladder:
    case LadderSide:
    case CustomSnap:
    case KidBlockUp:
    case KidBlockDown:
    case SlopeTL:
    case SlopeTR:
    case SlopeBL:
    case SlopeBR:
    case LucsterBubble:
    return true
}
return false
